- hosts: all
  tasks:
  - name: reload systemd daemons
    vars:
      file: vars/main.yml
      ansible_become_pass: '{{ linux_become_pass }}'
      ansible_become_ask_pass: true
    become_pass: '{{ linux_become_pass }}'
    become: yes
    become_method: sudo
    systemd:
      daemon_reload: yes

  - name: gather service facts
    ansible.builtin.service_facts:

  - name: Перезапуск сервиса
    become: yes
    become_method: sudo
    systemd:
      name: ssh
      state: restarted
      enabled: yes
