- hosts: all
  tasks:
  - name: reload systemd daemons
    vars:
      file: ../vaulted_vars.yml
      ansible_become_pass: '{{ ansible_ssh_pass }}'
      ansible_become_ask_pass: true
    become: yes
    become_method: sudo
    systemd:
      daemon_reload: yes

  - name: Перезапуск сервиса
    vars:
      file: ../vaulted_vars.yml
      ansible_become_pass: '{{ ansible_ssh_pass }}'
      ansible_become_ask_pass: true
    become: yes
    become_method: sudo
    systemd:
      name: '{{ systemctl_service }}'
      state: restarted
      enabled: yes
