- hosts: all
  gather_facts: yes
  vars:
    file: ../vaulted_vars.yml
    ansible_become_pass: '{{ ansible_ssh_pass }}'
    ansible_become_ask_pass: true
  remote_user: "{{ ansible_ssh_user }}"
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - roles/timesync
