# Отправка сообщения о завершении playbook в telegram
- name: Синхронизация времени
  hosts: all
  tasks:
      - name: Отправка результата в Telegram
        telegram:
            token: "{{ tokentele }}"
            chat_id: "{{ chat_id }}"
            msg: Синхронизация завершена
