# Отправка сообщения о завершении playbook в telegram
- name: Синхронизация времени
  hosts: all
  include_vars:
    dir: vars
    files_matching: mayn.yaml
  tasks:
    - name: Установка даты и времени
      apt:
        name: "{{ timesync_packages }}"
        state: present
    - name: Отправка результата в Telegram
      telegram:
        token: "{{ tokentele }}"
        chat_id: "{{ chat_id }}"
        msg: Синхронизация завершена
