# Отправка сообщения о завершении playbook в telegram
- name: Синхронизация времени
  hosts: all
  tasks:
      - name: Установка даты и времени
        include_vars:
          dir: vars
          files_matching: mayn.yml
          ignore_unknown_extensions: True
          extensions: ['', 'yaml', 'yml', 'json']
      - name: Установка даты и времени
        apt:
            name: "{{ timesync_packages }}"
            state: present
        #with_items: '{{ timesync_packages }}'
      #- name: Run ntpdate
        #command: '{{ timesync_ntpdate }} -u {{ timesync_server }}'
      - name: Отправка результата в Telegram
        telegram:
            #token: [tokentele]
            token: "{{ tokentele }}"
            chat_id: "{{ chat_id }}"
            msg: Синхронизация завершена
