# Отправка сообщения о завершении playbook в telegram
- name: Синхронизация времени
  hosts: all
  tasks:
      - name: Отправка результата в Telegram
        telegram:
            token: '326361299:AAEIvjAY4jHc75SCXyLhZ1cIbwJ0v6B6CDw'
            chat_id: 368904590
            msg: Синхронизация завершена
