# Отправка сообщения о завершении playbook в telegram
- name: Синхронизация времени
  hosts: all
  vars:
    send: []
  tasks:
      #- name: Be sure timesync packages are installed
        #apt:
            #name: '{{ item }}'
            #state: present
        #with_items: '{{ timesync_packages }}'
      #- name: Run ntpdate
        #command: '{{ timesync_ntpdate }} -u {{ timesync_server }}'
      - name: Отправка результата в Telegram
        telegram:
            #token: [tokentele]
            token: "{{ tokentele }}"
            chat_id: "{{ chat_id }}"
            msg: Синхронизация завершена
