- name: Gather the rpm package facts
  package_facts:
    manager: auto

- name: Print the rpm package facts
  debug:
    var: ansible_facts.packages

- name: Check whether a package called foobar is installed
  debug:
    msg: "{{ ansible_facts.packages['foobar'] | length }} versions of foobar are installed!"
  when: "'foobar' in ansible_facts.packages"

#- name: Обновление списка пакетов
  #apt:
    #update_cache: yes
#- name: Установка последней версии ntpdate
  #apt:
    #name: '{{ timesync_package }'
    #state: latest
